version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./.docker/php
    restart: "unless-stopped"
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: "unless-stopped"
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony_docker
      - ./.docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
      - database
